export const GET_DOGS = 'GET_DOGS';
export const SET_LOADING = 'SET_LOADING';
export const SET_SEARCH_BY_TYPE = 'SET_SEARCH_BY_TYPE';
export const SEARCH_DOGS = 'SEARCH DOGS';
export const RESET_DOGS = 'RESET DOGS';
export const ADD_DOG_FILTER = 'ADD_DOG_FILTER';
export const REMOVE_DOG_FILTER = 'REMOVE_DOG_FILTER';
export const CLEAR_ALL_DOG_FILTERS = 'CLEAR_ALL_DOG_FILTERS';