// Dog action types
export const GET_DOGS = 'GET_DOGS';
export const SET_LOADING = 'SET_LOADING';
export const SET_SEARCH_BY_TYPE = 'SET_SEARCH_BY_TYPE';
export const CACHE_DOG_SEARCH_TEXT = 'CACHE_DOG_SEARCH_TEXT';
export const SEARCH_DOGS = 'SEARCH DOGS';
export const RESET_DOGS = 'RESET DOGS';
export const ADD_DOG_FILTER = 'ADD_DOG_FILTER';
export const REMOVE_DOG_FILTER = 'REMOVE_DOG_FILTER';
export const CLEAR_ALL_DOG_FILTERS = 'CLEAR_ALL_DOG_FILTERS';
export const APPLY_DOG_FILTERS = 'APPLY_DOG_FILTERS';
export const SET_NUM_DOGS_TO_SHOW = 'SET_NUM_DOGS_TO_SHOW';

export const SET_IS_ADDING_NEW_DOG = 'SET_IS_ADDING_NEW_DOG';
export const SET_IS_ADDING_NEW_DOG_GROUP = 'SET_IS_ADDING_NEW_DOG_GROUP';
export const SET_IS_ADDING_NEW_DOG_LITTER = 'SET_IS_ADDING_NEW_DOG_LITTER';

export const DELETE_DOG_IN_APP_STATE = 'DELETE_DOG_FROM_APP_STATE';


export const UPDATE_DOG_REQUEST = 'UPDATE_DOG_REQUEST';
export const UPDATE_DOG_IN_APP_STATE = 'UPDATE_DOG_IN_APP_STATE';
export const UPDATE_DOG_FAILURE = 'UPDATE_DOG_FAILURE';

export const ADD_DOGS_TO_APP_STATE = 'ADD_DOGS_TO_APP_STATE';

// People action types

export const GET_FVA_COORDINATORS = 'GET_FVA_COORDINATORS';
export const GET_ALL_PEOPLE_NAMES = 'GET_ALL_PEOPLE_NAMES';
