const currentFostersData = [
  {
    "Name": "Bronte",
    "Notes": "",
    "Status": "fta",
    "Foster Name": "Andrea Mobine",
    "Foster Coordinator": "Rebecca",
    "Foster Coordinator Email": "rr.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "619-208-2225",
    "Email": "andrea.mobine@gmail.com",
    "Supplies": "no crate",
    "Address": "2883 Cooley Ave, San Diego, CA 92116",
    "Notes__1": "We have a 4 year old boxer.",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Yogi",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Crystal Honeck",
    "Foster Coordinator": "Rebecca",
    "Foster Coordinator Email": "rr.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "913-710-0911",
    "Email": "crystal.honeck@gmail.com",
    "Supplies": "has crate",
    "Address": "1833 Felton st. San Diego, CA 92102",
    "Notes__1": "has cats-prefers small dogs",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Rain",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Emma Castor",
    "Foster Coordinator": "Catalina",
    "Foster Coordinator Email": "cs.theanimalpad@gmail.com",
    "On website": "yes",
    "Phone": "858-248-2839",
    "Email": "emmacastor@gmail.com",
    "Supplies": "no crate",
    "Address": "4189 Utah st San Diego, CA 92104",
    "Notes__1": "has boxer, no kids",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Sweet Potato (mama)",
    "Notes": "8 puppies",
    "Status": "taken",
    "Foster Name": "Debra Zehr",
    "Foster Coordinator": "Catalina",
    "Foster Coordinator Email": "cs.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "619-417-4337",
    "Email": "skytreeground@gmail.com",
    "Supplies": "",
    "Address": "4427 Felton st. San Diego, CA 92116",
    "Notes__1": "has cats. needs small",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Jackie",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Carrie Neuner",
    "Foster Coordinator": "Catalina",
    "Foster Coordinator Email": "cs.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "630-803-2941",
    "Email": "carrieneuner@gmail.com",
    "Supplies": "",
    "Address": "2810 Calmar Drive, Escondido 92029",
    "Notes__1": "Ginger, 2 years, Yorkie mix, spayed, dog-friendly, Rudy, 9 months, Jack Russell mix, neutered, dog-friendly, 2 kids",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Berlin Pup: Azalea",
    "Notes": "",
    "Status": "fta",
    "Foster Name": "Sevag Kazanci",
    "Foster Coordinator": "Catalina",
    "Foster Coordinator Email": "cs.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(562) 2770316",
    "Email": "sevagkazanci@gmail.com",
    "Supplies": "",
    "Address": "3521 Gundry Ave. Long Beach, 90807",
    "Notes__1": "",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Cayman",
    "Notes": "",
    "Status": "fta",
    "Foster Name": "Alli Mathiason",
    "Foster Coordinator": "Jenn",
    "Foster Coordinator Email": "ja.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "612-715-3704",
    "Email": "armathiason@gmail.com",
    "Supplies": "no crate",
    "Address": "2321 29th st. San Diego, CA 92104",
    "Notes__1": "no dogs",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Ant",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Megan Casserly",
    "Foster Coordinator": "Jenn",
    "Foster Coordinator Email": "ja.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "443-463-8138",
    "Email": "mmcasserly@aol.com",
    "Supplies": "has crate",
    "Address": "3811 Marquette Place #4W, San Diego, CA 92106",
    "Notes__1": "no pets",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Peppercini",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Veronica Kemp",
    "Foster Coordinator": "Jenn",
    "Foster Coordinator Email": "ja.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "619-245-5167",
    "Email": "verokemp89@yahoo.com",
    "Supplies": "",
    "Address": "4554 Villas Dr, Bonita 91902",
    "Notes__1": "no pets, 2 older kids",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Adelaide Pup: Wallaby",
    "Notes": "",
    "Status": "fta",
    "Foster Name": "Amanda Bocanegra",
    "Foster Coordinator": "Jenn",
    "Foster Coordinator Email": "ja.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "951-581-2998",
    "Email": "amandanboca@gmail.com",
    "Supplies": "",
    "Address": "29478 Camino Cristal, Menifee 92584",
    "Notes__1": "no dogs, 2 kids",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Cascabel",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Tanya Ngo",
    "Foster Coordinator": "Jenn",
    "Foster Coordinator Email": "ja.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "714-757-5925",
    "Email": "ngottanya@gmail.com",
    "Supplies": "",
    "Address": "3950 Mahaila Ave, Apt C15, San Diego, CA 92122",
    "Notes__1": "No other dogs. Fostered Sugar Glider last",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Sia",
    "Notes": "aussie",
    "Status": "fta",
    "Foster Name": "Brooke Yapatangco (Finn)",
    "Foster Coordinator": "Jenn",
    "Foster Coordinator Email": "ja.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(619) 737-6008",
    "Email": "brooke.yaptangco@gmail.com",
    "Supplies": "",
    "Address": "234 Juniper St., San Diego, CA 92101",
    "Notes__1": "1 cat",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Athena (mama)",
    "Notes": "2 pups waiting",
    "Status": "taken",
    "Foster Name": "Karyn Rivera",
    "Foster Coordinator": "Catie",
    "Foster Coordinator Email": "cb.theanimalpad@gmail.com",
    "On website": "med hold",
    "Phone": "619-972-6728",
    "Email": "karynriv@outlook.com",
    "Supplies": "No crate",
    "Address": "11898 stonedale ct. San Diego, CA 92131",
    "Notes__1": "3 dogs",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Athena Pup: Hermes",
    "Notes": "",
    "Status": "fta",
    "Foster Name": "Karyn Rivera",
    "Foster Coordinator": "Catie",
    "Foster Coordinator Email": "cb.theanimalpad@gmail.com",
    "On website": "med hold",
    "Phone": "619-972-6728",
    "Email": "karynriv@outlook.com",
    "Supplies": "No crate",
    "Address": "11898 stonedale ct. San Diego, CA 92131",
    "Notes__1": "3 dogs",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Poi",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Amanda strack",
    "Foster Coordinator": "Catie",
    "Foster Coordinator Email": "cb.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "951-401-3864",
    "Email": "Amandastrack7@gmail.com",
    "Supplies": "has crate",
    "Address": "4684 cherokee ave, San Diego, CA 92116",
    "Notes__1": "Has 1 dog, 7 yrs old",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Skeeter",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Elsa Lachmayr",
    "Foster Coordinator": "Catie",
    "Foster Coordinator Email": "cb.theanimalpad@gmail.com",
    "On website": "",
    "Phone": 8583540963,
    "Email": "elachmay@gmail.com",
    "Supplies": "has crate",
    "Address": "4942 Mt. Etna Drive",
    "Notes__1": "Has dogs",
    "Homecheck": "FALSE",
    "": ""
  },
  {
    "Name": "Trix pup: Bran",
    "Notes": "",
    "Status": "fta",
    "Foster Name": "Kara Blohm",
    "Foster Coordinator": "Catie",
    "Foster Coordinator Email": "cb.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(616) 5668737",
    "Email": "karamarie1212@hotmail.com",
    "Supplies": "no crate",
    "Address": "2811 Howard Ave #B, San Diego, CA 92104",
    "Notes__1": "no pets",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Trix pup: Cheerios",
    "Notes": "",
    "Status": "fta",
    "Foster Name": "Erika Turner",
    "Foster Coordinator": "Catie",
    "Foster Coordinator Email": "cb.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(714) 315-0309",
    "Email": "thecalicogirl@gmail.com",
    "Supplies": "no crate",
    "Address": "4061 Kansas Street, San Diego, CA 92103",
    "Notes__1": "no pets",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Moira pup: Roland",
    "Notes": "Moira Pup",
    "Status": "taken",
    "Foster Name": "Kami Walker",
    "Foster Coordinator": "Catie",
    "Foster Coordinator Email": "cb.theanimalpad@gmail.com",
    "On website": "yes, apps",
    "Phone": "619-278- 1132",
    "Email": "kamiw@live.com",
    "Supplies": "no crate",
    "Address": "6307 acorn street San Diego CA 92115-",
    "Notes__1": "dogs and older kids",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Moira pup: Johnny",
    "Notes": "Moira Pup",
    "Status": "Taken",
    "Foster Name": "Kami Walker",
    "Foster Coordinator": "Catie",
    "Foster Coordinator Email": "cb.theanimalpad@gmail.com",
    "On website": "yes, apps",
    "Phone": "619-278- 1132",
    "Email": "kamiw@live.com",
    "Supplies": "no crate",
    "Address": "6307 acorn street San Diego CA 92115-",
    "Notes__1": "dogs and older kids",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Moira pup: David",
    "Notes": "Moira Pup",
    "Status": "Taken",
    "Foster Name": "Kami Walker",
    "Foster Coordinator": "Catie",
    "Foster Coordinator Email": "cb.theanimalpad@gmail.com",
    "On website": "yes, apps",
    "Phone": "619-278- 1132",
    "Email": "kamiw@live.com",
    "Supplies": "no crate",
    "Address": "6307 acorn street San Diego CA 92115-",
    "Notes__1": "dogs and older kids",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Paquito",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Jesus Gonzales",
    "Foster Coordinator": "Catie",
    "Foster Coordinator Email": "cb.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "860-888-5399",
    "Email": "jesusmgonzalez@yahoo.com",
    "Supplies": "no crate",
    "Address": "6273 Romo st San Diego, CA 92115",
    "Notes__1": "has dog",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Cayenne",
    "Notes": "temping for a potential fta",
    "Status": "Temp foster",
    "Foster Name": "Kristin Dove",
    "Foster Coordinator": "Catie",
    "Foster Coordinator Email": "cb.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "720-352-0826",
    "Email": "kristindove@yahoo.com",
    "Supplies": "",
    "Address": "5245 Mount alifan dr..San Diego, CA 92111",
    "Notes__1": "no pets, 7 year old son",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Athena Pup: Zeus",
    "Notes": "",
    "Status": "fta",
    "Foster Name": "Mikayla Rivera",
    "Foster Coordinator": "Catie",
    "Foster Coordinator Email": "cb.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "619-972-5615",
    "Email": "mikaylarvr@gmail.com",
    "Supplies": "",
    "Address": "443 20th St, San Diego, CA 92102",
    "Notes__1": "2 cats",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Berlin pup: Daisy",
    "Notes": "Daisy and Magnolia",
    "Status": "taken",
    "Foster Name": "Lisa Clark",
    "Foster Coordinator": "Joelle",
    "Foster Coordinator Email": "je.theanimalpad@gmail.com",
    "On website": "med hold.",
    "Phone": "760-420-6185",
    "Email": "clarkzoo@sbcglobal.net",
    "Supplies": "no crate",
    "Address": "3030 Blenkarne Drive, Carlsbad, CA 92008",
    "Notes__1": "Will take pregnant moms",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Berlin pup: Magnolia",
    "Notes": "Daisy and Magnolia",
    "Status": "taken",
    "Foster Name": "Lisa Clark",
    "Foster Coordinator": "Joelle",
    "Foster Coordinator Email": "je.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "760-420-6185",
    "Email": "clarkzoo@sbcglobal.net",
    "Supplies": "no crate",
    "Address": "3030 Blenkarne Dr",
    "Notes__1": "",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Hurley",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Kelly Dembicer",
    "Foster Coordinator": "Joelle",
    "Foster Coordinator Email": "je.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "916-705-4667",
    "Email": "kelly.dembicer@gmail.com",
    "Supplies": "no crate",
    "Address": "5469 San Onofre Terrace",
    "Notes__1": "",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Sonora (mama)",
    "Notes": "9 puppies",
    "Status": "taken",
    "Foster Name": "Patricia Cook-Zaragoza",
    "Foster Coordinator": "Joelle",
    "Foster Coordinator Email": "je.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "707-312-1070",
    "Email": "pacnapa@gmail.com",
    "Supplies": "",
    "Address": "6550 Ponto Dr. spc 127 carlsbad, CA 92011",
    "Notes__1": "",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Piquillo",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "VaNae Hamilton",
    "Foster Coordinator": "Kristin",
    "Foster Coordinator Email": "ks.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "617-869-8604",
    "Email": "vanaenhamilton@outlook.com",
    "Supplies": "no crate",
    "Address": "11080 W Ocean Air Dr. Apt 110, San Diego, CA 92130",
    "Notes__1": "Kristin asked to be FC for her! no dogs, no kids",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Nugget",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "D'hana Bishop",
    "Foster Coordinator": "Kristin",
    "Foster Coordinator Email": "ks.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "973-513-5370",
    "Email": "dahnabishop1@gmail.com",
    "Supplies": "",
    "Address": "3711 Bancroft St, San Diego, CA 92104",
    "Notes__1": "no dogs, no kids",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Ginger pup: Broccoli",
    "Notes": "",
    "Status": "fta",
    "Foster Name": "Claire Mcateer",
    "Foster Coordinator": "Kristin",
    "Foster Coordinator Email": "ks.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(617) 7638739",
    "Email": "clairemcateer97@gmail.com",
    "Supplies": "no crate",
    "Address": "1028 14th St, Apt 306, San Diego, CA 92101",
    "Notes__1": "1 dog",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Cubanelle",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Nicole Wyne",
    "Foster Coordinator": "Kristin",
    "Foster Coordinator Email": "ks.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "443-812-3695",
    "Email": "nicole.a.wyne@gmail.com",
    "Supplies": "no crate",
    "Address": "4921 saratoga ave. San Diego, CA 92107",
    "Notes__1": "tap alumni",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Bambino",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Lauren Markey",
    "Foster Coordinator": "mysti",
    "Foster Coordinator Email": "ms.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(419) 3086139",
    "Email": "laurensmarkey@gmail.com",
    "Supplies": "has crate",
    "Address": "2720 Broadway, Apt. 27, San Diego, CA 92102",
    "Notes__1": "none",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Adelaide Pup: Kookaburra",
    "Notes": "",
    "Status": "FTA",
    "Foster Name": "Tiffany Johnson",
    "Foster Coordinator": "Mysti",
    "Foster Coordinator Email": "ms.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(619) 3011642",
    "Email": "scenery79@hotmail.com",
    "Supplies": "",
    "Address": "6161 Amaya Dr. La Mesa 91942",
    "Notes__1": "None",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Tostada",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Colleen Carty",
    "Foster Coordinator": "Chante",
    "Foster Coordinator Email": "chanteMF.theanimalpad@gmail.com",
    "On website": "foster hold",
    "Phone": "703-963-2003",
    "Email": "cartych@gmail.com",
    "Supplies": "",
    "Address": "971 Loring St. Apt 4 San Diego, CA 92109",
    "Notes__1": "no dogs",
    "Homecheck": "FALSE",
    "": ""
  },
  {
    "Name": "Kaden",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Heather Rivera",
    "Foster Coordinator": "Chante",
    "Foster Coordinator Email": "chanteMF.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "862-219-2712",
    "Email": "heather.rivera26@gmail.com",
    "Supplies": "",
    "Address": "5998 alcala park unit 8274",
    "Notes__1": "2 cats",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Kirby",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Loni Kaye",
    "Foster Coordinator": "Chante",
    "Foster Coordinator Email": "chantemf.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "818-618-6688",
    "Email": "loni.kaye@gmail.com",
    "Supplies": "has crate",
    "Address": "2932 1st Avenue, San Diego, CA 92103",
    "Notes__1": "no pets or kids",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Moira (mama)",
    "Notes": "",
    "Status": "foster",
    "Foster Name": "Carly Boerman",
    "Foster Coordinator": "Chante",
    "Foster Coordinator Email": "chanteMF.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(858) 8298137",
    "Email": "cboerman3@gmail.com",
    "Supplies": "has crate",
    "Address": "",
    "Notes__1": "",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Moira pup: Alexis",
    "Notes": "Moira pup",
    "Status": "taken",
    "Foster Name": "Carly Boerman",
    "Foster Coordinator": "Chante",
    "Foster Coordinator Email": "chantemf.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(858) 8298137",
    "Email": "cboerman3@gmail.com",
    "Supplies": "has crate",
    "Address": "13936 Davenport Ave. San Diego, CA 92129",
    "Notes__1": "no dogs",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Miranda",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Allison Weeks",
    "Foster Coordinator": "Adrielle",
    "Foster Coordinator Email": "aw.theanimalpad@gmail.com",
    "On website": "no-med hold",
    "Phone": "760-385-3738",
    "Email": "peticularlyperfect@gmail.com",
    "Supplies": "no crate",
    "Address": "1940 via scott escondido, CA 92026",
    "Notes__1": "Need to be neutered/spayed",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Habanero",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Adrielle Wai",
    "Foster Coordinator": "Adrielle",
    "Foster Coordinator Email": "aw.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "858-863-3552",
    "Email": "adriellew@gmail.com",
    "Supplies": "",
    "Address": "",
    "Notes__1": "",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Athena pup: Hercules",
    "Notes": "",
    "Status": "fta",
    "Foster Name": "Hailey Dideriksen",
    "Foster Coordinator": "Adrielle",
    "Foster Coordinator Email": "aw.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "858-229-1464",
    "Email": "hdideriksen67@midwestern.edu",
    "Supplies": "",
    "Address": "16755 Coyote Bush Dr, Unit 19, San Diego, CA 92127",
    "Notes__1": "",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Lefty",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Alyssa Lindahl",
    "Foster Coordinator": "Adrielle",
    "Foster Coordinator Email": "aw.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "619-922-7694",
    "Email": "alyssaevjen@yahoo.com",
    "Supplies": "Has crate",
    "Address": "13551 Brett Harte Drive, Lakeside 92040",
    "Notes__1": "has 2 young kids. only puppies or small young dogs please",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Athena pup: Achilles",
    "Notes": "",
    "Status": "fta",
    "Foster Name": "Amber Sole",
    "Foster Coordinator": "Adrielle",
    "Foster Coordinator Email": "aw.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "858-204-2339",
    "Email": "ambersanderson@sbcglobal.net",
    "Supplies": "",
    "Address": "25645 Paseo la Cresta, Laguna Niguel 92677",
    "Notes__1": "",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Ginger pup: Parsnip",
    "Notes": "",
    "Status": "fta",
    "Foster Name": "Jenni Cook",
    "Foster Coordinator": "Adrielle",
    "Foster Coordinator Email": "aw.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(858) 2302251",
    "Email": "jennifer.michelle.fitness@gmail.com",
    "Supplies": "",
    "Address": "443 Mesa Way, San Diego, CA 92037",
    "Notes__1": "no pets",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Ginger pup: Pepper",
    "Notes": "",
    "Status": "fta",
    "Foster Name": "Sam Yellen (Garret)",
    "Foster Coordinator": "Adrielle",
    "Foster Coordinator Email": "aw.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(619) 9929099",
    "Email": "syellen35@gmail.com",
    "Supplies": "",
    "Address": "4440 Kansas Street, San Diego, CA 92116",
    "Notes__1": "no pets",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Prague",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Christina Poudrier",
    "Foster Coordinator": "Andrea",
    "Foster Coordinator Email": "ar.theanimalpad@gmail.com",
    "On website": "med hold-pregnant",
    "Phone": "858-322-9931",
    "Email": "crip003@hotmail.com",
    "Supplies": "has crate",
    "Address": "8523 Capricorn Way unit 46, San Diego, CA 92126",
    "Notes__1": "has dog",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Adelaide Pup: Croc",
    "Notes": "",
    "Status": "fta",
    "Foster Name": "Samantha Buffington",
    "Foster Coordinator": "Andrea",
    "Foster Coordinator Email": "ar.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(609) 5139412",
    "Email": "spmarie7@gmail.com",
    "Supplies": "",
    "Address": "3302 Waco Street, San Diego, CA 92117",
    "Notes__1": "no dogs",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Fresno",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Sarah Bryce",
    "Foster Coordinator": "andrea",
    "Foster Coordinator Email": "ar.theanimalpad@gmail.com",
    "On website": "possible ff",
    "Phone": "508-250-5852",
    "Email": "sperdoni@gmail.com",
    "Supplies": "has crate",
    "Address": "",
    "Notes__1": "no pets",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Mr. Man (Manmosa)",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Rachel Gasca",
    "Foster Coordinator": "Jenna",
    "Foster Coordinator Email": "jf.theanimalpad@gmail.com",
    "On website": "no, med hold",
    "Phone": "619-994-3808",
    "Email": "rgasca87@gmail.com",
    "Supplies": "has crate",
    "Address": "944 29th st. San Diego, CA 92102",
    "Notes__1": "no pets",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Bebe",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Carly Henek",
    "Foster Coordinator": "Jenna",
    "Foster Coordinator Email": "jf.theanimalpad@gmail.com",
    "On website": "no need",
    "Phone": "646-226-6841",
    "Email": "carlyhenek@gmail.com",
    "Supplies": "yes - #28",
    "Address": "4933 Coronado Ave. San Diego, CA 92107",
    "Notes__1": "has dog",
    "Homecheck": "FALSE",
    "": ""
  },
  {
    "Name": "Pam (mama)",
    "Notes": "4 puppies",
    "Status": "foster",
    "Foster Name": "Darcie McBeth",
    "Foster Coordinator": "Jenna",
    "Foster Coordinator Email": "jf.theanimalpad@gmail.com",
    "On website": "medical hold",
    "Phone": "619-405-2482",
    "Email": "darcie.mcbeth@gmail.com",
    "Supplies": "yes",
    "Address": "3518 Mission Mesa Way San Diego, CA 92120",
    "Notes__1": "",
    "Homecheck": "FALSE",
    "": ""
  },
  {
    "Name": "Palomina",
    "Notes": "probably will adopt.",
    "Status": "taken",
    "Foster Name": "Bianca Melgazo",
    "Foster Coordinator": "Jenna",
    "Foster Coordinator Email": "jf.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "949-429-9676",
    "Email": "bvmelgazo@gmail.com",
    "Supplies": "no crate",
    "Address": "1515 Everview Rd. San Diego, CA 92110",
    "Notes__1": "no pets. just lost her senior pit",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Willow (mama)",
    "Notes": "",
    "Status": "fta",
    "Foster Name": "Lara Kalaf",
    "Foster Coordinator": "Jenna",
    "Foster Coordinator Email": "jf.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "619-823-1112",
    "Email": "lara.kf@gmail.com",
    "Supplies": "no crate",
    "Address": "1970 columbia street, unit 307",
    "Notes__1": "",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Lupo",
    "Notes": "Palomito",
    "Status": "foster",
    "Foster Name": "Paul DeNigris",
    "Foster Coordinator": "Jenna",
    "Foster Coordinator Email": "jf.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "440-567-1593",
    "Email": "denigrispaul@gmail.com",
    "Supplies": "yes - #42",
    "Address": "2050 Pacific Beach Dr, San Diego, CA 92109",
    "Notes__1": "No other pets",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Moby",
    "Notes": "Toby",
    "Status": "temp foster",
    "Foster Name": "Erin Whyte Chisdak",
    "Foster Coordinator": "Jenna",
    "Foster Coordinator Email": "jf.theanimalpad@gmail.com",
    "On website": "yes",
    "Phone": "619-813-5463",
    "Email": "erinchisdak@gmail.com",
    "Supplies": "No crate",
    "Address": "",
    "Notes__1": "",
    "Homecheck": "FALSE",
    "": ""
  },
  {
    "Name": "Esperanza",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Jeannette Sanchez",
    "Foster Coordinator": "Jenna",
    "Foster Coordinator Email": "jf.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "203-822-3432",
    "Email": "jeannettesanchez716@gmail.com",
    "Supplies": "No crate",
    "Address": "4620 Hawley Blvd, APT #5, San Diego, CA 92116",
    "Notes__1": "no other pets, no kids",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Solovino",
    "Notes": "",
    "Status": "foster",
    "Foster Name": "Barbara Thunder",
    "Foster Coordinator": "Jenna",
    "Foster Coordinator Email": "jf.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "760-271-5128",
    "Email": "barbarathunder@gmail.com",
    "Supplies": "no crate",
    "Address": "1053 Woodlake Dr. Cardiff, CA 92007",
    "Notes__1": "",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Lou",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "DiMee Zeoli",
    "Foster Coordinator": "Jenna",
    "Foster Coordinator Email": "jf.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "856-449-5923",
    "Email": "dmzeoli@yahoo.com",
    "Supplies": "no crate",
    "Address": "4035 Atascadero dr, San Diego, CA 92107",
    "Notes__1": "none",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Coffee (mama)",
    "Notes": "8 puppies",
    "Status": "taken",
    "Foster Name": "Dana Lally",
    "Foster Coordinator": "Jenna",
    "Foster Coordinator Email": "jf.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "858-336-9191",
    "Email": "danalally@gmail.com",
    "Supplies": "no crate",
    "Address": "",
    "Notes__1": "",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Serrano",
    "Notes": "",
    "Status": "foster",
    "Foster Name": "Diana Reyes",
    "Foster Coordinator": "Jenna",
    "Foster Coordinator Email": "jf.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "619-621-4578",
    "Email": "reyesdiana15@yahoo.com",
    "Supplies": "no crate",
    "Address": "2279 Ocean view blvd. San Diego, CA 92113",
    "Notes__1": "Girlfriend of one of Justin's good friends/cilent. Lives with boyfriend who has another dog and wants to do a meet and greet at kennels",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Aloha",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Adrian Lawrence",
    "Foster Coordinator": "",
    "Foster Coordinator Email": "celeste.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "",
    "Email": "lawrenceas@yahoo.com",
    "Supplies": "",
    "Address": "688 13th st apt 432 San Diego, CA 92101",
    "Notes__1": "",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Coral pup: Victoria",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Bethany  Labarge",
    "Foster Coordinator": "celeste",
    "Foster Coordinator Email": "celeste.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "619-876-0363",
    "Email": "Bethany@LaBargePhotography.com",
    "Supplies": "has crate",
    "Address": "801 26th street #15, San Diego, CA 92102",
    "Notes__1": "No pets, Kids: Yes, I have a 12 year old son",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Antigua",
    "Notes": "with fta see below",
    "Status": "taken",
    "Foster Name": "Duane Besse Besse",
    "Foster Coordinator": "Kara",
    "Foster Coordinator Email": "kdc.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "619-717-0693",
    "Email": "dbesse@operamail.com",
    "Supplies": "crate and pen",
    "Address": "3535 Madison Ave unit 115 San Diego, CA 92116",
    "Notes__1": "has dogs",
    "Homecheck": "FALSE",
    "": ""
  },
  {
    "Name": "Chimichurri",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Jenn Wood",
    "Foster Coordinator": "Kara",
    "Foster Coordinator Email": "kdc.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "858-652-2900",
    "Email": "jennwood92@gmail.com",
    "Supplies": "has 2 crates",
    "Address": "425 W Beech St 429 San Diego, CA 92101",
    "Notes__1": "has 1 mini aussie",
    "Homecheck": "FALSE",
    "": ""
  },
  {
    "Name": "Trix pup: Pebbles",
    "Notes": "Adopted",
    "Status": "FTA",
    "Foster Name": "Paul Rappa",
    "Foster Coordinator": "Kara",
    "Foster Coordinator Email": "kdc.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(831) 2775421",
    "Email": "paulrappa@gmail.com",
    "Supplies": "",
    "Address": "8092 Nightingale Way, San Diego, CA 92123",
    "Notes__1": "no pets",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Hilo",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Charito Redona",
    "Foster Coordinator": "kara",
    "Foster Coordinator Email": "kdc.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "858-405-8486",
    "Email": "pinchepatrona@yahoo.com",
    "Supplies": "no crate",
    "Address": "7481 Hyatt Street, San Diego, CA 92111",
    "Notes__1": "My landlord/neighbor/good friend has two huskies that I take care of every now and then",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Roxy",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Jennifer Beaudette",
    "Foster Coordinator": "Kara",
    "Foster Coordinator Email": "kdc.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "619-249-8725",
    "Email": "jenniferbeaudette@gmail.com",
    "Supplies": "no crate",
    "Address": "4580 Ohio st. unit 15 San Diego, CA 92116",
    "Notes__1": "1 chi",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Diamond",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Siana  Amos",
    "Foster Coordinator": "Casey",
    "Foster Coordinator Email": "cp.theanimalpad@gmail.com",
    "On website": "possible ff",
    "Phone": "310-904-9479",
    "Email": "siananoelle@gmail.com",
    "Supplies": "no crate",
    "Address": "3233 Herman Avenue, Unit 2 San Diego, CA 92104",
    "Notes__1": "male terrier mix, approx. 8 years old",
    "Homecheck": "FALSE",
    "": ""
  },
  {
    "Name": "Cricket",
    "Notes": "",
    "Status": "fta",
    "Foster Name": "Tammie Nguyen",
    "Foster Coordinator": "Casey",
    "Foster Coordinator Email": "cp.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "858-220-2844",
    "Email": "t30nguye@gmail.com",
    "Supplies": "crate",
    "Address": "6761 Estrella Ave San Diego, CA 92120",
    "Notes__1": "1 dog",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Piri-piri",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Jessica Reeves",
    "Foster Coordinator": "Casey",
    "Foster Coordinator Email": "cp.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "619-876-3948",
    "Email": "jo.theanimalpad@gmail.com",
    "Supplies": "no crate",
    "Address": "1643 Dale St. San Diego, CA 92102",
    "Notes__1": "",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Sanuk",
    "Notes": "",
    "Status": "FTA",
    "Foster Name": "Madison Garrett",
    "Foster Coordinator": "Alex",
    "Foster Coordinator Email": "ah.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "714-722-1207",
    "Email": "maddyg98@gmail.com",
    "Supplies": "no crate",
    "Address": "3833 Midway dr. apt 321",
    "Notes__1": "no pets",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Adelaide Pup: TimTam",
    "Notes": "",
    "Status": "FTA",
    "Foster Name": "Amy Bieber",
    "Foster Coordinator": "Alex",
    "Foster Coordinator Email": "ah.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(626) 8623111",
    "Email": "amy@amypaturel.com",
    "Supplies": "",
    "Address": "30615 McGowans Pass, Murrieta 92563",
    "Notes__1": "",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Berlin Pup: Clover",
    "Notes": "",
    "Status": "fta",
    "Foster Name": "April Manusig",
    "Foster Coordinator": "Alex",
    "Foster Coordinator Email": "ah.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "661-304-5997",
    "Email": "aprilmanusig@gmail.com",
    "Supplies": "Has crate",
    "Address": "1361 Caminito Gabaldon F San Diego, CA 92108",
    "Notes__1": "no dogs.",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Berlin Pup: Magnolia",
    "Notes": "",
    "Status": "fta",
    "Foster Name": "Jennie Vance",
    "Foster Coordinator": "Alex",
    "Foster Coordinator Email": "ah.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(760) 434-9908",
    "Email": "jvance065@gmail.com",
    "Supplies": "",
    "Address": "4718 Edinburgh Dr., Carlsbad 92010",
    "Notes__1": "",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Jalapeno",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Anya Tomkiewicz",
    "Foster Coordinator": "Alex",
    "Foster Coordinator Email": "ah.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(415) 3202482",
    "Email": "anya.tomkiewicz@gmail.com",
    "Supplies": "has crate",
    "Address": "3940 Idaho Street, #12 San Diego, CA 92104",
    "Notes__1": "No other dogs.",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Kokomo",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Tiffany Moreno",
    "Foster Coordinator": "Alex",
    "Foster Coordinator Email": "ah.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(619) 7632925",
    "Email": "nena9551@gmail.com",
    "Supplies": "",
    "Address": "455 Ballantyne St  Unit 11, El Cajon 92020",
    "Notes__1": "2 smalls dogs, no kids",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Wheatie",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Connie Liu",
    "Foster Coordinator": "Cat",
    "Foster Coordinator Email": "cje.theanimalpad@gmail.com",
    "On website": "yes",
    "Phone": "858-699-5350",
    "Email": "connieliu08@gmail.com",
    "Supplies": "has 2 crates (one is #17)",
    "Address": "1102 Skylark Dr. La Jolla, CA 92037",
    "Notes__1": "no pets, no kids",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Cady",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Claire Walker",
    "Foster Coordinator": "Cat",
    "Foster Coordinator Email": "cje.theanimalpad@gmail.com",
    "On website": "ff",
    "Phone": "815-382-5565",
    "Email": "clairewalker18@gmail.com",
    "Supplies": "",
    "Address": "450 J st. unit 3271 San Diego, CA 92101",
    "Notes__1": "no pets",
    "Homecheck": "FALSE",
    "": ""
  },
  {
    "Name": "Snail",
    "Notes": "",
    "Status": "fta",
    "Foster Name": "Angela Burke",
    "Foster Coordinator": "Cat",
    "Foster Coordinator Email": "cje.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(520) 4002653",
    "Email": "angelaeburke@yahoo.com",
    "Supplies": "",
    "Address": "9393 De Camp Dr, La Mesa 91942",
    "Notes__1": "has 1 cat",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Trix pup: Kix",
    "Notes": "",
    "Status": "FTA",
    "Foster Name": "Brian Konisky",
    "Foster Coordinator": "Joy",
    "Foster Coordinator Email": "jsj.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(603) 6862451",
    "Email": "brian.konisky@gmail.com",
    "Supplies": "no crate",
    "Address": "2674 Hornblend St. Unit E, San Diego, CA 92109",
    "Notes__1": "1 cat",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Trix pup: Captain Crunch",
    "Notes": "",
    "Status": "FTA",
    "Foster Name": "Richard Wheeler",
    "Foster Coordinator": "Joy",
    "Foster Coordinator Email": "jsj.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "941-720-0293",
    "Email": "wheelerrichard@outlook.com",
    "Supplies": "no crate",
    "Address": "3178 Polk Ave, San Diego, CA 92104",
    "Notes__1": "1 female feline, 3 years old",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Moana (mama)",
    "Notes": "10 puppies",
    "Status": "taken",
    "Foster Name": "Andrea Mattingly",
    "Foster Coordinator": "Joy",
    "Foster Coordinator Email": "jsj.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(858) 9458175",
    "Email": "a.mattingly1230@gmail.com",
    "Supplies": "no crate",
    "Address": "4809 Fairport Way, San Diego, CA 92130",
    "Notes__1": "Hazel - female min pin; almost 13 years old; no issues. Smokey - male shepherd mix; almost 8 years old; can be protective at first.",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Adelaide Pup: Tas",
    "Notes": "",
    "Status": "fta",
    "Foster Name": "Ashley Howieson",
    "Foster Coordinator": "Joy",
    "Foster Coordinator Email": "jsj.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(619) 9857844",
    "Email": "ashleyhowieson@gmail.com",
    "Supplies": "no crate",
    "Address": "9451 Carlton Oaks Drive, Unit E, Santee 92071",
    "Notes__1": "has a dog",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Adelaide Pup: Vegemite",
    "Notes": "",
    "Status": "fta",
    "Foster Name": "Kari Coe",
    "Foster Coordinator": "Joy",
    "Foster Coordinator Email": "jsj.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(760) 5337622",
    "Email": "vcmomof4@aol.com",
    "Supplies": "no crate",
    "Address": "29494 Miller Road, Valley Center, CA 92082",
    "Notes__1": "Tortoise, dog, cat",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Arbol",
    "Notes": "",
    "Status": "",
    "Foster Name": "Krystal Reynoso",
    "Foster Coordinator": "Joy",
    "Foster Coordinator Email": "jsj.theanimalpad@gmail.com",
    "On website": "apps",
    "Phone": "951-852-2471",
    "Email": "krystalSreynoso@gmail.com",
    "Supplies": "no crate",
    "Address": "3932 9th ave, San Diego, CA 92103",
    "Notes__1": "no pets.",
    "Homecheck": "FALSE",
    "": ""
  },
  {
    "Name": "Poblano",
    "Notes": "",
    "Status": "taking soon",
    "Foster Name": "Donna L Ross",
    "Foster Coordinator": "Joy",
    "Foster Coordinator Email": "jsj.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "619-808-9819",
    "Email": "courseross@gmail.com",
    "Supplies": "no crate",
    "Address": "1556 Bridgeview Dr. San Diego, CA 92105",
    "Notes__1": "no pets",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Hula (mama)",
    "Notes": "4 puppies",
    "Status": "taken",
    "Foster Name": "Sarah Fleming",
    "Foster Coordinator": "Mishel",
    "Foster Coordinator Email": "mf.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "858) 337-6798",
    "Email": "sierrasarah@yahoo.com",
    "Supplies": "",
    "Address": "4417 Tivoli St. San Diego, CA 92107",
    "Notes__1": "Jack- 1 1/2 year old chi mix, neutered, Sadie and Ellie - 5-6 year old cats, spayed, Sadie doesn’t mind respectful dogs, Ellie stays away from Jack!, Oliver and Peanut - 3-4 year old bunnies, fixed",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Lilikoi",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Becky Callender",
    "Foster Coordinator": "Mishel",
    "Foster Coordinator Email": "mf.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "662-352-9228",
    "Email": "becky.callender@yahoo.com",
    "Supplies": "No crate",
    "Address": "3911 Centraloma dr. San Diego, CA 92107",
    "Notes__1": "has 2 dogs",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Kona",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Daniella McGuire",
    "Foster Coordinator": "Mishel",
    "Foster Coordinator Email": "mf.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "408-839-3552",
    "Email": "daniellamcguire@comcast.net",
    "Supplies": "has crate",
    "Address": "1372 1/2 Grand Ave San Diego, CA 92109",
    "Notes__1": "no pets, no kids, wants small or medium",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Ancho",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Dena Slattery",
    "Foster Coordinator": "Mishel",
    "Foster Coordinator Email": "mf.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "317-514-6464",
    "Email": "denaslattery@gmail.com",
    "Supplies": "has crate",
    "Address": "4572 Bancroft St, San Diego, CA 92116",
    "Notes__1": "no dogs, no kids",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Flynn (mama)",
    "Notes": "pregnant mama",
    "Status": "taken",
    "Foster Name": "Elli-Ana Hauser",
    "Foster Coordinator": "Jena",
    "Foster Coordinator Email": "jh1.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "619-729-2328",
    "Email": "elli.anah@yahoo.com",
    "Supplies": "has crate",
    "Address": "4004 Risa Court, San Diego, CA 92124",
    "Notes__1": "Marley is a 4 year old German Shepard, -Danny is a 9 year old Mini Schnauze",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Jagger",
    "Notes": "ff",
    "Status": "taken",
    "Foster Name": "Mary-Kate Catton",
    "Foster Coordinator": "jena",
    "Foster Coordinator Email": "jh1.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "619-366-5445",
    "Email": "mkcatton@yahoo.com",
    "Supplies": "has crate-returning 7/24",
    "Address": "473 Summerhill Court",
    "Notes__1": "14 year old miniature schnauzer",
    "Homecheck": "FALSE",
    "": ""
  },
  {
    "Name": "Joss",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Jane Bishop",
    "Foster Coordinator": "jena",
    "Foster Coordinator Email": "jh1.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(843) 3008344",
    "Email": "Chalidajbishop@gmail.com",
    "Supplies": "has crate",
    "Address": "982 Broadway, apt 104, Chula Vista 91911",
    "Notes__1": "none",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Babe",
    "Notes": "ff",
    "Status": "fta",
    "Foster Name": "Sarah Eadie",
    "Foster Coordinator": "Jena",
    "Foster Coordinator Email": "jh1.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(530) 4009197",
    "Email": "saraheadie2@gmail.com",
    "Supplies": "has crate",
    "Address": "935 Laguna Drive Apt 12, Carlsbad 92008",
    "Notes__1": "no pets",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Moira pup: Patrick",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Tracy Frank",
    "Foster Coordinator": "Jena",
    "Foster Coordinator Email": "jh1.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "818-321-1480",
    "Email": "tracyafrank@gmail.com",
    "Supplies": "has crate",
    "Address": "3825 Arnold Ave. San Diego, CA 92104",
    "Notes__1": "no pets or kids",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Moira pup: Twyla",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Cera Hayes",
    "Foster Coordinator": "Jena",
    "Foster Coordinator Email": "jh1.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(760) 5253305",
    "Email": "h_cera@yahoo.com",
    "Supplies": "",
    "Address": "1366 San Vicente rd, Ramona 92065",
    "Notes__1": "no pets, 5 year old daughter",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Pasilla",
    "Notes": "",
    "Status": "fta",
    "Foster Name": "Lauren Few",
    "Foster Coordinator": "Jena",
    "Foster Coordinator Email": "jh1.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(828) 243-8540",
    "Email": "lrfew22@gmail.com",
    "Supplies": "getting a crate",
    "Address": "2736 Monroe Ave, San Diego, CA 92116",
    "Notes__1": "UPDATED: Mr. Carson - labradoodle - 12.5; he has no problems with other dogs, and has many dog friends that he spends times with.",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Banana",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Fernanda Stout",
    "Foster Coordinator": "Jena",
    "Foster Coordinator Email": "jh1.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(619) 450-9541",
    "Email": "chavarelaf@gmail.com",
    "Supplies": "has crate",
    "Address": "452 Concepcion Avenue",
    "Notes__1": "1 dog, 2 kids (age 5)",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Pequin",
    "Notes": "",
    "Status": "fta",
    "Foster Name": "Rebecca Tessimond",
    "Foster Coordinator": "Jena",
    "Foster Coordinator Email": "jh1.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(978) 9730897",
    "Email": "tessim.reb@gmail.com",
    "Supplies": "no crate",
    "Address": "1980 Froude St., San Diego, CA 92107",
    "Notes__1": "I have one dog, Melvin, 8 years old, chihuahua mix.  Large dogs sometimes intimidate him.",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Scallop",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Cecilia Li",
    "Foster Coordinator": "Brittany",
    "Foster Coordinator Email": "bls.theanimalpad@gmail.com",
    "On website": "apps-going to lena when clear",
    "Phone": "760-258-7547",
    "Email": "ceciliali1009@gmail.com",
    "Supplies": "has crate",
    "Address": "1177 Crystal Lane El cajon, CA 92020",
    "Notes__1": "no other pets",
    "Homecheck": "FALSE",
    "": ""
  },
  {
    "Name": "Ghost",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Julia Shi",
    "Foster Coordinator": "Brittany",
    "Foster Coordinator Email": "bls.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(949) 6488473",
    "Email": "julias@usc.edu",
    "Supplies": "",
    "Address": "6182 Blue Dawn Trail, San Diego, CA 92130",
    "Notes__1": "no pets, no kids",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Adelaide Pup: Darwin",
    "Notes": "",
    "Status": "fta",
    "Foster Name": "Brittany Overfelt",
    "Foster Coordinator": "Brittany",
    "Foster Coordinator Email": "bls.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(619) 9339828",
    "Email": "brittany.overfelt@gmail.com",
    "Supplies": "",
    "Address": "1000 greenfield drive #12, El Cajon 92021",
    "Notes__1": "no dogs",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Journey",
    "Notes": "",
    "Status": "fta",
    "Foster Name": "Kelly Gonzales",
    "Foster Coordinator": "Michelle",
    "Foster Coordinator Email": "mmf.theanimalpad@gmail.com",
    "On website": "fta",
    "Phone": "858-243-8463",
    "Email": "mamakelly4@gmail.com",
    "Supplies": "",
    "Address": "5749 El Cabo Court, San Diego, CA 92124",
    "Notes__1": "no pets",
    "Homecheck": "FALSE",
    "": ""
  },
  {
    "Name": "Tesla",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Vanessa Baczewski",
    "Foster Coordinator": "michelle",
    "Foster Coordinator Email": "mmf.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "301-956-3173",
    "Email": "vaczewski@yahoo.com",
    "Supplies": "no crate",
    "Address": "1475 island ave 3703 San Diego, CA 92101",
    "Notes__1": "no pets",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Anaheim",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Madison Mercurio",
    "Foster Coordinator": "Michelle",
    "Foster Coordinator Email": "mmf.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "562-489-4227",
    "Email": "madimercurio@gmail.com",
    "Supplies": "",
    "Address": "5534 Soledad Mountain Rd, La Jolla 92037",
    "Notes__1": "Possible FTA Anaheim. Needs to know about her possible broken leg though. No other dogs in home, just a 3 year old  VERY dog friendly cat",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Turbo",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Ariana Bartsch-Green",
    "Foster Coordinator": "Megan",
    "Foster Coordinator Email": "mfk.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "559-287-9205",
    "Email": "ariana.b.green@gmail.com",
    "Supplies": "has crate",
    "Address": "3975 Nobel Dr. unit 300 San Diego, CA 92122",
    "Notes__1": "9 yo female yellow lab",
    "Homecheck": "FALSE",
    "": ""
  },
  {
    "Name": "Slug",
    "Notes": "",
    "Status": "temp",
    "Foster Name": "Jonathan Restivo",
    "Foster Coordinator": "Megan",
    "Foster Coordinator Email": "mfk.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "860-334-9509",
    "Email": "jonathan.restivo@gmail.com",
    "Supplies": "no crate",
    "Address": "1440 Columbia Street, #1011 San Diego, CA 92101",
    "Notes__1": "no pets",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Flea",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Brianne Leati",
    "Foster Coordinator": "Megan",
    "Foster Coordinator Email": "mfk.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "(858) 3499228",
    "Email": "brianneraelene@gmail.com",
    "Supplies": "has crate",
    "Address": "7110 Mimosa Drive, Carlsbad 92011",
    "Notes__1": "",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Chipotle",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Christine Asaro",
    "Foster Coordinator": "Bridget",
    "Foster Coordinator Email": "bco.theanimalpad@gmail.com",
    "On website": "needs bio?",
    "Phone": "619-210-6949‬",
    "Email": "asarobiz1@gmail.com",
    "Supplies": "crate 22",
    "Address": "213 el cajon blvd. #22 el cajon, CA 92020",
    "Notes__1": "no other pets",
    "Homecheck": "FALSE",
    "": ""
  },
  {
    "Name": "Teddy",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Amanda Holbrook",
    "Foster Coordinator": "Bridget",
    "Foster Coordinator Email": "bco.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "804-543-2378",
    "Email": "aholbrook@sandiego.edu",
    "Supplies": "",
    "Address": "867 Opal Street San Diego, CA 92109",
    "Notes__1": "Current roommate has a female golden doodle that is 2 years old.",
    "Homecheck": "",
    "": "#REF!"
  },
  {
    "Name": "Slash",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Michelle Bridwall",
    "Foster Coordinator": "Melinda",
    "Foster Coordinator Email": "mw.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "415-377-9579",
    "Email": "mlbridwell@hotmail.com",
    "Supplies": "no crate",
    "Address": "820 W G st. apt 238 San Diego, CA 92101",
    "Notes__1": "1 pit/lab",
    "Homecheck": "",
    "": ""
  },
  {
    "Name": "Hatch",
    "Notes": "Kennel Volunteer",
    "Status": "",
    "Foster Name": "Mehak Kirpalani",
    "Foster Coordinator": "Melinda",
    "Foster Coordinator Email": "mw.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "201-893-2570",
    "Email": "mehaka16@gmail.com",
    "Supplies": "crate",
    "Address": "9135 Judicial Drive, Unit 3523, San Diego, CA 92122",
    "Notes__1": "1 Chi, no kids",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Kennedy",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Allison Hurst",
    "Foster Coordinator": "Amanda",
    "Foster Coordinator Email": "as.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "703-201-3719",
    "Email": "alli.hurst7@gmail.com",
    "Supplies": "crate #39",
    "Address": "1554 Hornblend St. Unit 1 San Diego, CA 92109",
    "Notes__1": "no dogs",
    "Homecheck": "TRUE",
    "": ""
  },
  {
    "Name": "Mojave",
    "Notes": "",
    "Status": "taken",
    "Foster Name": "Lucy Lou",
    "Foster Coordinator": "Amanda",
    "Foster Coordinator Email": "as.theanimalpad@gmail.com",
    "On website": "",
    "Phone": "858-900-5331",
    "Email": "lucylou12345@gmail.com",
    "Supplies": "crate",
    "Address": "11548 Creek Road Poway, CA 92064",
    "Notes__1": "",
    "Homecheck": "",
    "": ""
  }
]

module.exports = currentFostersData;